services:
  db:
    image: docker.io/postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: teac_example_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - teac_example:/var/lib/postgresql/data
volumes:
  teac_example:
